trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- bash: |
   pip install hovercraft
  displayName: 'Bash - Setup'

- bash: |
   cd presentations/
   hovercraft introduction.rst output/introduction
   hovercraft ingest.rst output/ingest
   hovercraft compute.rst output/compute
   hovercraft consume.rst output/consume
   hovercraft expose.rst output/expose
   hovercraft endnotes.rst output/endnotes
   
  displayName: 'Bash - run hovercraft'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/presentations/output'
    artifactName: 'drop'
