trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- bash: |
   pip install hovercraft
  displayName: 'Bash - Setup'

- bash: |
   cd docs/presentations/
   hovercraft introduction.rst output/compute
   hovercraft introduction.rst output/consume
   hovercraft introduction.rst output/expose
   hovercraft introduction.rst output/ingest
   hovercraft introduction.rst output/introduction
  displayName: 'Bash - run hovercraft'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/docs/presentations/output'
    artifactName: 'drop'
